name: Build Package and Upload to GitHub Releases

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run: python -m build
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: dist/*
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
